easy_admin:
    site_name: 'a-birkett.co.uk Admin'

    entities:
        BlockedAddresses:
            label: 'Blocked Addresses'
            class: App\Entity\BlockedAddress

        Comments:
            class: App\Entity\Comment

        Posts:
            class: App\Entity\Post

        Pages:
            class: App\Entity\Page

        Tweets:
            class: App\Entity\Tweet

        Users:
            class: App\Entity\User
